### PR TITLE
Add setup.py and other configuration dotfiles.

### PR DESCRIPTION
**Pull request by jason-neal**
Add setup.py for the package.

.travis.yml for Travis CI and .coveragerc for coverage settings.
.codeclimate.yml to configure. code climate inspection.
.setup.cfg enables `python setup.py test`
.readthedocs.yml for rtd setup.

A single test to check ci server works.

### CODE REVIEW

**Comment by DanielAndreasen** [comment]
Does this work both for 3.x and 2.7? If so I see no reason not to merge.
Btw, Jason, you should have priviliges to merge now.

**Comment by jason-neal** [comment]
I am not sure about on 2.7, I will check this but it should be fine.

Yes I do see the privileges. I was just giving time to allow others the chance to review it if you wish before making the changes. (i.e. I see that you thumbs up-ed it.)
I have other changes coming that build on this PR but trying to keep them as separate PRs.

**Comment by DanielAndreasen** [comment]
Sounds great. When you have checked for 2.7 then it's fine for me if you merge it.

**Comment by jason-neal** [comment]
The Travis CI 2.7 build works (It does `python setup.py install`), which I already knew. 

The only  python version specific is the readthedocs build setting which is set to py3.5 but that doesn't affect the operation of the package. (its a choice 2.7 or 3.5)

**Pull request merged**
