### PR TITLE
add starobs mode to visibility

### PR DESCRIPTION
**Pull request by j-faria**
I need help with this, the plot should work but I can't reproduce what comes out of **staralt**...

The output of  `python visibility.py HD967 -m starobs`

starobs_min

The output from starobs

starobs

### CODE REVIEW

**Comment by DanielAndreasen** [comment]
Phew... Do you know why it isn't working? And do you have the code for the new function from somewhere?

**Comment by j-faria** [comment]
The altitude seems fine, it's just a time shift of ~3 months. I have no idea why...
The main function is `pyasl.eq2hor`, the rest of the code is adapted from the night visibility plot. Is that what you are asking?

**Comment by DanielAndreasen** [comment]
Yes, that is what I am asking. Do we have the same behaviour with other targets? And if so, is the shift the same?

**Comment by j-faria** [comment]
The shift seems to be the same:

starobs_mine2
starobs2

**Comment by jason-neal** [comment]
I haven't been able to run this on python2  as I get segmention faults...

```
(obstools) python visibility.py HD967 -m starobs
Segmentation fault (core dumped)
```

Trying to run this in python 3 I get this issue.
 ```
python visibility.py HD967 -m starobs
Could not find target: HD967
Calculating visibility for HD967
2016
La Silla Observatory
Traceback (most recent call last):
  File "visibility.py", line 611, in <module>
    StarObsPlot(date=date, targets=targets, observatory=args.site)
  File "visibility.py", line 208, in StarObsPlot
    for t in range(airmass2.size): airmassformat.append("%2.2f" % airmass2[t])
IndexError: too many indices for array


```
I hope this is a helpful clue.

**Comment by DanielAndreasen** [comment]
That looks strange. A `segmentation fault` from Python. Can you run without `-m starobs`?

**Comment by j-faria** [comment]
Should work now in Python 3, still wrong results though. 

Can you try running in Python 2 with `-v` as in
`python -v visibility.py HD967 -m starobs`
to see what is failing? I guess that's is some package giving the segmentation fault...

**Comment by jason-neal** [comment]
It seg faults with and without -m starobs.
`python -v visibility HD967`
ends with 
...
import scipy.linalg.misc # precompiled from /home/jneal/anaconda2/envs/obstools/lib/python2.7/site-packages/scipy/linalg/misc.pyc
# /home/jneal/anaconda2/envs/obstools/lib/python2.7/site-packages/scipy/linalg/blas.pyc matches /home/jneal/anaconda2/envs/obstools/lib/python2.7/site-packages/scipy/linalg/blas.py
import scipy.linalg.blas # precompiled from /home/jneal/anaconda2/envs/obstools/lib/python2.7/site-packages/scipy/linalg/blas.pyc
dlopen("/home/jneal/anaconda2/envs/obstools/lib/python2.7/site-packages/scipy/linalg/_fblas.so", 2);
Segmentation fault (core dumped)
```
It seams to be an issue with the pip scipy wheel. If I install scipy using conda then it works.

**Comment by jason-neal** [comment]
Running with py27 in this case I get an encode error with 
```
python visibility.py hd967 -m starobs
Calculating visibility for hd967
2016
La Silla Observatory
Traceback (most recent call last):
  File "visibility.py", line 609, in <module>
    StarObsPlot(date=date, targets=targets, observatory=args.site)
  File "visibility.py", line 173, in StarObsPlot
    ax.set_xticklabels(map(calendar.month_name.__getitem__, months), fontsize=10)
  File "/home/jneal/miniconda3/envs/obstools27/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 2909, in set_xticklabels
    minor=minor, **kwargs)
  File "/home/jneal/miniconda3/envs/obstools27/lib/python2.7/site-packages/matplotlib/axis.py", line 1575, in set_ticklabels
    tick.label1.set_text(tick_label)
  File "/home/jneal/miniconda3/envs/obstools27/lib/python2.7/site-packages/matplotlib/text.py", line 1206, in set_text
    self._text = '%s' % (s,)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 3: ordinal not in range(128)

```
I think I have worked out that this is because my locale is set to portugal. When I run the calender line separately in ipython it returns months in Portuguese.  
```
import locale
locale.getlocale()
('pt_PT', 'UTF-8')
```
This still doesn't fix your original problem though. I have had a mission trying to actually run your code.

**Comment by j-faria** [comment]
Fixed for now. It prints the month abbreviation which doesn't have weird characters ;)
Not the best solution, admittedly.

**Comment by jason-neal** [comment]
I think the issue is with your sampling, You are only taking one measurement of altitude at the same time of day. e.g. 0000UT. ( I assume you would like maximum altitude?)

If you increase the sampling rate i.e from 1 to 1/24 it will sample the position every hour.
```
# JD array
jdbinsize = 1./24  # every hour
```
But the result I get is very messy. 

But if I add hours to the start datetime I can shift the position of the plot around. e.g. 
`jd_start = pyasl.jdcnv(dt.datetime(date, 1, 1, 3))`

It might be a good idea to use masks to remove the values that fall during day time or something like
i.e. altaz[0][sunpos_alatz[0] < 0] = np.nan  
I tried this but it the Tkinter complained about non-finite values. 
or for below horizon altaz[0][alatz[0] < 0] = np.nan  

Hope this helps narrow down the issue.

**Comment by jason-neal** [comment]
Ah ha! The StarObs plot is for "Altitudes at middle dark time". The dark mid-time for each day needs to be calculated and then use that for your jds (I assume the hour changes). Then it should be bale to reproduce the starobs plot.

**Comment by j-faria** [comment]
It's fixed!!

starobs_mine3


Thanks a lot Jason, that was indeed the problem! 
Now I use pyephem to calculate the middle dark time (the Sun's anti transit) and it's working.

**Comment by j-faria** [comment]
Ready to merge? :D

**Comment by DanielAndreasen** [comment]
I guess, but maybe we can just clean the code (there are a lot of lines with commented code) :)

**Comment by jason-neal** [comment]
No problem. It was a nice challenge.
I would agree with Daniel about the commented code. Especially the comments copied from the previous function should probably be cleaned up.
Also is there any plotting code left from the previous function that shouldn't be? It was a bit overwhelming for me so I did not check it all.

**Comment by jason-neal** [comment]
Maybe add a note/label that it is calculated at mid-dark time, Just to be clear for users.

**Comment by DanielAndreasen** [comment]
I think it is safe to merge now.

**Comment by DanielAndreasen** [comment]
This feels so prof.! :D

**Comment by jason-neal** [comment]
Yea looks good.

**Pull request merged**
