### PR TITLE
Add start for ESO archive

### PR DESCRIPTION
**Pull request by DanielAndreasen**
This is related to issue #1. Definitely not done, but a start. Some suggestions are welcome. Documentations for this can be found [here](http://astroquery.readthedocs.io/en/latest/eso/eso.html)

### CODE REVIEW

**Comment by jason-neal** [comment]
I was thinking... 
I might be an idea to make the username just a keyword. So you don't need to specify it when just searching for data.

I know argparse has mutually exclusive flags but I am not sure about mutually inclusive. 
You could make it so you only need to pass username when actually need to login.
e.g. username require when you want to  `--download` the files.
```
python eso_archive.py --object Aldebaran --download --username xxxxx 
```

```
python eso_archive.py --object Aldebaran --download 
Warning: You need to supply a username to download data from the eso archive.
```

What do you think?

**Comment by DanielAndreasen** [comment]
I think it's a solid suggestion. Let me have a look

**Comment by jason-neal** [comment]
Also following the [astroquery.eso](https://astroquery.readthedocs.io/en/latest/eso/eso.html) docs you can have automatic login with [astropy.config](http://docs.astropy.org/en/stable/config/index.html).

So maybe the mutually inclusive is constraint is not a good idea, incase you want to have it stored automatically.

Just have it as a keyword.

**Comment by DanielAndreasen** [comment]
Seems like this project is dead, and I want to clear out my open PRs

**Pull request closed without merging**
